spring.application.name=storyGen


spring.datasource.url={{ENTER YOUR RDS ENDPOINT URL}}
spring.datasource.username={{ENTER YOUR USERNAME}}
spring.datasource.password={{ENTER YOUR PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

