package com.example.demo.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.HashMap;
import java.util.Map;

@Service
public class n8nservice {

    @Value("${n8n.webhook.url:https://srisaketh.app.n8n.cloud/webhook/Storyorchestrator}")
    private String n8nWebhookUrl;

    public String generateText(String prompt) {

        try {
            RestTemplate restTemplate = new RestTemplate();

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            Map<String, Object> requestBody = new HashMap<>();
            requestBody.put("storyId", "1");
            requestBody.put("playerId", "player001");
            requestBody.put("userPrompt", prompt);

            HttpEntity<Map<String, Object>> entity =
                    new HttpEntity<>(requestBody, headers);

            ResponseEntity<String> responseEntity = restTemplate.postForEntity(
                    n8nWebhookUrl,
                    entity,
                    String.class
            );

            String responseBody = responseEntity.getBody();
            if (responseBody == null || responseBody.trim().isEmpty()) {
                return "No story content generated by n8n.";
            }

            try {
                ObjectMapper mapper = new ObjectMapper();
                JsonNode root = mapper.readTree(responseBody);
                
                StringBuilder storyText = new StringBuilder();
                
                if (root.has("story") && root.get("story").has("currentScene") && root.get("story").get("currentScene").has("summary")) {
                    storyText.append(root.get("story").get("currentScene").get("summary").asText()).append("\n\n");
                }
                
                if (root.has("dialogue") && root.get("dialogue").has("conversations")) {
                    JsonNode convs = root.get("dialogue").get("conversations");
                    if (convs.isArray()) {
                        for (JsonNode conv : convs) {
                            String speaker = conv.has("speaker") ? conv.get("speaker").asText() : "";
                            String text = conv.has("text") ? conv.get("text").asText() : "";
                            if (!speaker.isEmpty() && !text.isEmpty()) {
                                storyText.append(speaker).append(": \"").append(text).append("\"\n");
                            }
                        }
                    }
                }
                
                if (storyText.length() > 0) {
                    return storyText.toString().trim();
                }
            } catch (Exception parseEx) {
                // Fall back to raw response body if parsing fails
            }

            return responseBody;

        } catch (Exception e) {
            e.printStackTrace();
            return "Error calling n8n webhook: " + e.getMessage();
        }
    }
}